// mockData.js

export const products = [
  { _id: 'p1', name: 'Wireless Bluetooth Headphones', category: 'Electronics', price: 59.99, stock: 120, rating: 4.5 },
  { _id: 'p2', name: 'Running Shoes', category: 'Footwear', price: 89.99, stock: 80, rating: 4.2 },
  { _id: 'p3', name: 'Coffee Maker', category: 'Home Appliances', price: 120.0, stock: 40, rating: 4.0 },
  { _id: 'p4', name: 'Smartphone Case', category: 'Accessories', price: 15.99, stock: 300, rating: 4.7 },
  { _id: 'p5', name: 'Yoga Mat', category: 'Fitness', price: 25.5, stock: 150, rating: 4.3 },
  { _id: 'p6', name: 'Electric Toothbrush', category: 'Personal Care', price: 39.99, stock: 200, rating: 4.4 },
  { _id: 'p7', name: 'Gaming Mouse', category: 'Electronics', price: 45.0, stock: 90, rating: 4.6 },
  { _id: 'p8', name: 'LED Desk Lamp', category: 'Home Decor', price: 29.99, stock: 130, rating: 4.1 },
  { _id: 'p9', name: 'Water Bottle', category: 'Outdoor', price: 12.99, stock: 250, rating: 4.0 },
  { _id: 'p10', name: 'Backpack', category: 'Accessories', price: 49.99, stock: 110, rating: 4.3 },

  { _id: 'p11', name: 'Wireless Charger', category: 'Electronics', price: 22.99, stock: 160, rating: 4.2 },
  { _id: 'p12', name: 'Fitness Tracker', category: 'Wearables', price: 99.99, stock: 70, rating: 4.5 },
  { _id: 'p13', name: 'Sunglasses', category: 'Accessories', price: 65.0, stock: 90, rating: 4.4 },
  { _id: 'p14', name: 'Bluetooth Speaker', category: 'Electronics', price: 35.0, stock: 100, rating: 4.3 },
  { _id: 'p15', name: 'Desk Organizer', category: 'Office', price: 20.0, stock: 140, rating: 4.0 },
  { _id: 'p16', name: 'Electric Kettle', category: 'Home Appliances', price: 55.0, stock: 80, rating: 4.1 },
  { _id: 'p17', name: 'Notebook', category: 'Stationery', price: 5.99, stock: 500, rating: 4.6 },
  { _id: 'p18', name: 'Ballpoint Pens (Pack of 10)', category: 'Stationery', price: 3.5, stock: 600, rating: 4.7 },
  { _id: 'p19', name: 'Office Chair', category: 'Furniture', price: 150.0, stock: 30, rating: 4.2 },
  { _id: 'p20', name: 'Wireless Keyboard', category: 'Electronics', price: 45.99, stock: 90, rating: 4.4 },

  { _id: 'p21', name: 'Smartwatch', category: 'Wearables', price: 199.99, stock: 60, rating: 4.5 },
  { _id: 'p22', name: 'Laptop Stand', category: 'Accessories', price: 34.99, stock: 110, rating: 4.3 },
  { _id: 'p23', name: 'Portable Hard Drive 1TB', category: 'Electronics', price: 75.0, stock: 70, rating: 4.4 },
  { _id: 'p24', name: 'Mechanical Keyboard', category: 'Electronics', price: 85.0, stock: 40, rating: 4.6 },
  { _id: 'p25', name: 'Noise Cancelling Headphones', category: 'Electronics', price: 120.0, stock: 50, rating: 4.7 },
  { _id: 'p26', name: 'Electric Fan', category: 'Home Appliances', price: 40.0, stock: 75, rating: 4.0 },
  { _id: 'p27', name: 'LED Monitor 24 inch', category: 'Electronics', price: 150.0, stock: 35, rating: 4.3 },
  { _id: 'p28', name: 'Smart Light Bulb', category: 'Home Automation', price: 20.0, stock: 120, rating: 4.1 },
  { _id: 'p29', name: 'Coffee Grinder', category: 'Home Appliances', price: 25.0, stock: 60, rating: 4.0 },
  { _id: 'p30', name: 'Wireless Earbuds', category: 'Electronics', price: 70.0, stock: 95, rating: 4.5 },

  { _id: 'p31', name: 'Travel Mug', category: 'Outdoor', price: 15.0, stock: 150, rating: 4.3 },
  { _id: 'p32', name: 'Laptop Backpack', category: 'Accessories', price: 60.0, stock: 80, rating: 4.4 },
  { _id: 'p33', name: 'Yoga Block', category: 'Fitness', price: 12.5, stock: 120, rating: 4.2 },
  { _id: 'p34', name: 'Fitness Resistance Bands', category: 'Fitness', price: 18.0, stock: 140, rating: 4.3 },
  { _id: 'p35', name: 'Desk Clock', category: 'Home Decor', price: 22.0, stock: 130, rating: 4.1 },
  { _id: 'p36', name: 'HDMI Cable', category: 'Electronics', price: 10.0, stock: 400, rating: 4.6 },
  { _id: 'p37', name: 'USB-C Hub', category: 'Electronics', price: 35.0, stock: 90, rating: 4.4 },
  { _id: 'p38', name: 'Wireless Gaming Controller', category: 'Electronics', price: 50.0, stock: 70, rating: 4.5 },
  { _id: 'p39', name: 'Smart Thermostat', category: 'Home Automation', price: 130.0, stock: 40, rating: 4.2 },
  { _id: 'p40', name: 'Action Camera', category: 'Electronics', price: 150.0, stock: 45, rating: 4.4 },

  { _id: 'p41', name: 'Electric Scooter', category: 'Transportation', price: 350.0, stock: 25, rating: 4.3 },
  { _id: 'p42', name: 'Wireless Security Camera', category: 'Home Automation', price: 90.0, stock: 60, rating: 4.2 },
  { _id: 'p43', name: 'Bluetooth Car Adapter', category: 'Automotive', price: 30.0, stock: 100, rating: 4.0 },
  { _id: 'p44', name: 'Portable Projector', category: 'Electronics', price: 220.0, stock: 35, rating: 4.1 },
  { _id: 'p45', name: 'Electric Grill', category: 'Home Appliances', price: 75.0, stock: 50, rating: 4.0 },
  { _id: 'p46', name: 'Smart Door Lock', category: 'Home Automation', price: 180.0, stock: 30, rating: 4.3 },
  { _id: 'p47', name: 'Digital Photo Frame', category: 'Home Decor', price: 55.0, stock: 70, rating: 4.2 },
  { _id: 'p48', name: 'Electric Blanket', category: 'Home Appliances', price: 60.0, stock: 40, rating: 4.1 },
  { _id: 'p49', name: 'Wireless Mouse', category: 'Electronics', price: 25.0, stock: 110, rating: 4.4 },
  { _id: 'p50', name: 'Smart Water Bottle', category: 'Fitness', price: 45.0, stock: 75, rating: 4.0 },
];


